sudo: false
language: node_js
node_js:
- 9
- 8
env:
  global:
  - S3_BUCKET=catbox-s3.fhemberger.github.com
  - S3_REGION=eu-central-1
  - secure: ByD+bryRnPpWLjiFkhSrGEgghZkJIf3h3q9i3czfGT2Sw0SfKQexGlo9Cdo206EUv4xUP57xb0BHwM92T8/gsu28dvGjg/QCy3plf8fvryxrYxYMUg+uF/IryD99vxnfHA3jmQvTQtCCXvTsh/2jmmUrURdqu0U46k+r6p+PifA=
  - secure: DnuYtbXieLTzRinbroyQYOjz1zZiXjtLpjBsvESyQX/uaSBWB489YXZbZ8p1lCtG5js9yYbUlNkTK+8tzCDyGnsszKm9QiVuFn6zrCBqNxfR2kq2zplEYwtzRUoIL4+k5YLoPQ21NsMQ4uTNKM1n3zHk/6ygI5xudfvoK/zXdXo=
